### ISSUE TITLE
Update Text Feature?

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#101]
I think we've lost the ability to update the projects that are already downloaded.  Do we have this implemented and I just can't figure it out or did we lose the UI for this?

**Comment by jag3773** [comment]
I see that if you delete the resource then it may be downloaded again, that is not very intuitive however.  There should be an update button somewhere.  Possibly, the update button could go next to the Delete button, if we could do two columns there, e.g.:

Update     |     Delete

**Comment by bknatterud** [comment]
The way the text update is working right is that if you press the main update button on the home screen any currently downloaded texts will be updated.

**Comment by jag3773** [comment]
OK, got it, that works.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
