### ISSUE TITLE
Review Poetry Formatting

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#102]
Jonah 2 looks OK, but Lamentations 1 doesn't look like poetry.

**Comment by bknatterud** [comment]
Jesse, did you mean to say that Lamentations 1 looks ok but Jonah 2 does not look right? On my devices it is Lamentations that does look like poetry.

Let me know.

**Comment by bknatterud** [comment]
I think we are interpreting the markup correctly. See the USFM files here...

https://api.unfoldingword.org/udb/txt/1/udb-en/25-LAM.usfm
https://api.unfoldingword.org/udb/txt/1/udb-en/32-JON.usfm

Let me know if we are doing something wrong.

**Comment by jag3773** [comment]
That's fine then, just wanted to make sure we weren't missing any codes.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
