### ISSUE TITLE
Font Size Issues

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#104]
Font size and line spacing is a problem.  I think the easiest way to fix this problem would be to add a point size changer, so that people can make the text smaller or larger.  Pinch to zoom would be a good way to implement this.

The font size in OBS looks good, but is off in the Bible.

**Comment by PeeJWeeJ** [comment]
Now a Duplicate of #129

**Comment by PeeJWeeJ** [comment]
Dealt with in latest Beta
