### ISSUE TITLE
Share Icon

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#105]
The share icon on the main screen does not indicate "sharing", but rather download.  It also does not match what is used elsewhere in the app.

**Comment by PeeJWeeJ** [comment]
FYI, the button on the main screen is currently intended as more of a load button rather than a share button since it's the only place a user can go in-app to load shared versions.

**Comment by jag3773** [comment]
OK, I think the new UI mockup will address this.

**Comment by PeeJWeeJ** [comment]
Closing since discussion is taking place on https://github.com/unfoldingWord-dev/uw-android/issues/125
