### ISSUE TITLE
Update Button

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#117]
Now that there is a share icon in the top bar, it's odd to have the update button below the top bar.

The share and update buttons should both be somewhere on the main screen.  For that matter, it would make sense to put the settings button at the same level as well.  I'd like Sam to weigh on this.

**Comment by jag3773** [comment]
Related to #105

**Comment by PeeJWeeJ** [comment]
Closing since discussion is taking place on https://github.com/unfoldingWord-dev/uw-android/issues/125
