### ISSUE TITLE
No Bug Reporting

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#120]
We have no way to report bugs in app.

**Comment by PeeJWeeJ** [comment]
Is there a mockup for how this should be implemented? Or should it be similar to tK? If so, where should it be accessible by users?

**Comment by PeeJWeeJ** [comment]
@jag3773 @bknatterud Is there any direction on this issue?

**Comment by bknatterud** [comment]
Yes. Add the bug reporting like the tK app has.

**Comment by PeeJWeeJ** [comment]
Where should the report button go?

**Comment by bknatterud** [comment]
There may be another place at some point in the future but for now let's put it under the settings area.

**Comment by bknatterud** [comment]
Just need token

**Comment by bknatterud** [comment]
Got token. Next build will have the token in it.

**Comment by PeeJWeeJ** [comment]
Added in latest beta.
