### ISSUE TITLE
Changing Base URL Crashes App

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#122]
After changing the base URL to https://api.unfoldingword.org/demo/uw/txt/2/catalog.json I hit the refresh/download button, which then caused an app crash.  Subsequently, going into the list of languages for OBS causes a crash.

**Comment by bknatterud** [comment]
This is fixed so the app will not crash. The issue is that the catalog.json file has a bad locale "en-x-demo1".

The next release for uW will check this so it will not crash the app.
