### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#124]
See https://app.testfairy.com/projects/1370651-unfoldingword/builds/1816391/sessions/2/?accessToken=ABjJ9UsrSdS5sMaDjbJaVOOo2dc

**Comment by PeeJWeeJ** [comment]
It appears this crash was due to a duplicate key from http://td.unfoldingword.org/exports/langnames.json I haven't reproduced this in the latest beta, so it may have been a bug in that build. Re-open if it occurs again.
