### ISSUE TITLE
Ugly Green

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#125]
The update link here is ugly next to the main UI green.  https://s3.amazonaws.com/testfairy/screenshots/1370651/1816391/13573386/3_1a3eaf06f44aed1b5f398ef0f2cc89c1df93d43f_o.jpg

**Comment by PeeJWeeJ** [comment]
What should be done about this?

Also related to #117. This should generally be re-designed.

**Comment by sampeckham** [comment]
Just chatted briefly with @bknatterud about the home screen earlier. I will design a new home screen to resolve the clashing colours (sorry colors!).

The actual shade of green is wrong in iOS. Android phone not playing ball so will need to check that too.

**Comment by PeeJWeeJ** [comment]
@sampeckham If the colors are wrong, can you get us the correct hex values?

**Comment by jag3773** [comment]
"Next Chapter" is also an ugly green.

**Comment by PeeJWeeJ** [comment]
Updated to the new color scheme on iOS
