### ISSUE TITLE
Audio Not Synchronized with Stories

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#126]
Full screencast: https://app.testfairy.com/projects/1370651-unfoldingword/builds/1816391/sessions/1/?accessToken=Ou8Q/z7fb4YiR7EG6NJabcZ5zhQ

The audio does not change when the story is changed.

**Comment by PeeJWeeJ** [comment]
related to #127

**Comment by PeeJWeeJ** [comment]
Fixed in latest Beta, Audio changes properly when changing chapters.
