### ISSUE TITLE
No Way to Download Audio

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#128]
Full screencast: https://app.testfairy.com/projects/1370651-unfoldingword/builds/1816391/sessions/1/?accessToken=Ou8Q/z7fb4YiR7EG6NJabcZ5zhQ

There doesn't appear to be anyway to download audio in the UI.  We had discussed have that as a second entry on this screen: https://s3.amazonaws.com/testfairy/screenshots/1370651/1816391/13573386/11_ad9bb62dfc248268bb183d147bf68ce2f328820c_o.jpg .  In other words, one entry for text and one for audio.

**Comment by PeeJWeeJ** [comment]
Two questions, 

1. Should the only option for user be to download an entire version of audio/video? Keep in mind, this will eventually be hundreds of MegaBytes.

2. Is that version screen the only place they can download the media? Or, for instance, should users be prompted to download the media when they select the audio/video from the reading screen, but it hasn't been downloaded?

**Comment by PeeJWeeJ** [comment]
2 More questions:

Is media verification shown to users in any way? 
What should happen if media fails to verify?

**Comment by jag3773** [comment]
Same thing as text -- except that we haven't implemented the signing of media yet on the server side.

**Comment by jag3773** [comment]
For the first 2 questions:

1. This is tricky from a UI and data standpoint.  I think downloading a book at a time is the most natural, but I'm not entirely sure on that.  @sampeckham what do you think?

2. Yes, they should be prompted to download if they try to use it but it's not there.

**Comment by PeeJWeeJ** [comment]
For now I'll have the option in the version screen be to download all, and the option while reading will only download the page/chapter.

**Comment by PeeJWeeJ** [comment]
Implemented in latest Beta.
