### ISSUE TITLE
Share menu select all and many

### ISSUE THREAD

**Issue by PeeJWeeJ** [unfoldingWord-dev/uw-android#132]
Add the ability to select all and select many while sharing versions.

**Comment by dwsolberg** [comment]
Is this for this release or not? I'm assuming it's not because we haven't talked about it and don't have a UI for it. Also, with all the audio options, it's going to get confusing, not to mention huge, huge sizes.

Also, not sure if this even makes sense in iOS at least.

**Comment by jag3773** [comment]
Has become a dup of #145
