### ISSUE TITLE
Explanation of 3 checking levels

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/uw-android#133]
Requested that all 3 checking levels appear more than just at the first time the app is opened.

**Comment by dwsolberg** [comment]
The relevant checking information also appears when tapping the "i" button on the chooser screen. What other places would you like to see the checking information?

**Comment by jag3773** [comment]
The request is to be able to see all 3 levels at the same time.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by PeeJWeeJ** [comment]
Is this simply a request to consider in future redesigns? Or does it need to be implemented? If so, how?

**Comment by dwsolberg** [comment]
@jag3773  I'm not clear. Where should we put the button/UI for all three levels at once?

**Comment by jag3773** [comment]
This could be added pretty easily to the settings.

**Comment by PeeJWeeJ** [comment]
Would it be ok to instead add an info (i) button to the tab bar on the home screen that simply shows the popup that comes up when the app is first run? That seems like a more consistent UX.

**Comment by dwsolberg** [comment]
I think putting it in Settings is okay, although maybe we should rename this to app info and use the "i" icon.

**Comment by PeeJWeeJ** [comment]
Added for next release

**Comment by dwsolberg** [comment]
done on ios
