### ISSUE TITLE
app gets stuck in language chooser screen. the ...

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/uw-android#138]
Notes
======
app gets stuck in language chooser screen. the back button on the device and in the app do not work.

Environment
======
Environment Key | Value
:----: | :----:
version | 2.3.0
build | 188
UDID | d757cfb5eb3ededd
Android Release | 5.1.1
Android SDK | 22
Brand | lge
Device | d850

**Comment by jag3773** [comment]
The only way out is to select a language and then hit the back arrow to get back to the main screen.

**Comment by PeeJWeeJ** [comment]
Fixed for next release
