### ISSUE TITLE
Fix Main Screen

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#139]
The main screen should look like this: https://invis.io/HK4J550XM.

**Comment by dwsolberg** [comment]
This is the new screen. I was under the impression this was for the next version. Can you confirm you want to update this now?

**Comment by jag3773** [comment]
The main screen design is definitely for right now.  There are buttons all over the main screen and it does not make any sense currently.

**Comment by dwsolberg** [comment]
Done on iOS.

**Comment by PeeJWeeJ** [comment]
Done in Android
