### ISSUE TITLE
Low/High Audio Versions

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#140]
The app is supposed to provide access to a low or high quality audio version, but there is no choice in the app.

**Comment by PeeJWeeJ** [comment]
Where are the wire frames of how this is supposed to work in the UI?

**Comment by dwsolberg** [comment]
Right now, I'm downloading the high quality versions. I was assuming that the low quality ones were for streaming.

**Comment by jag3773** [comment]
Low quality should always be the default.

**Comment by jag3773** [comment]
@sampeckham any ideas on how/where this should appear

**Comment by sampeckham** [comment]
Design for the language selector, and audio/video download, with modal to select quality level. I would anticipate, if you keep the default tick option, that would be replicated in settings to turn it off again. (Feel free to leave that feature out for now if it pushes the next release too much.)
[OBS Language Download - style guide.pdf](https://github.com/unfoldingWord-dev/uw-android/files/31190/OBS.Language.Download.-.style.guide.pdf)
[OBS Language Download Modal.pdf](https://github.com/unfoldingWord-dev/uw-android/files/31189/OBS.Language.Download.Modal.pdf)
[OBS Language Download.pdf](https://github.com/unfoldingWord-dev/uw-android/files/31188/OBS.Language.Download.pdf)

**Comment by PeeJWeeJ** [comment]
Is this design taking into consideration the possibility of multiple versions for a language? There are no example of this and I'm thinking having as many as 3 rows for each version may become unwieldy and confusing as more versions are added.

**Comment by jag3773** [comment]
@sampeckham Perfect, I love it!

I think @PeeJWeeJ is referring to multiple Bible versions per language, right?  We should get a screen for that too @sampeckham .

**Comment by sampeckham** [comment]
I would suggest multiple versions are just listed as if another language. 

English - en - udb
English - en - ulb

Until you get to a point where there are more than 3 versions for a language, we should them move to a language selection with another sub screen/activity listing versions. (Like a tree structure or master detail view would be)

**Comment by jag3773** [comment]
Agreed, that was my initial thought @sampeckham

**Comment by PeeJWeeJ** [comment]
A couple additional questions:
1. How dose the user get to the version info? The info that expands when the info button is pressed in the current version
2. What is the expected behavior when the user taps and audio or video row?

**Comment by sampeckham** [comment]
1. version info would pop up as a modal when they tap the checking level icon. 
2. Tapping the row would trigger download modal.

**Comment by PeeJWeeJ** [comment]
Table rows are generally supposed to do the same or similar thing, no?

**Comment by dwsolberg** [comment]
This looks good to me. A couple of notes, though:

1. Sam noted that multiple languages should use something like I "English - en - udb" and 
"English - en - ulb" The concept is good, but I'm going to keep the full names as they are now unless I hear differently. For example "Dynamic Bible" and "Literal Bible" as entries under English.

2. Tapping the audio or video row should work the same way as the text row. Unless I hear differently, tapping any of the three rows will either download the content if not already downloaded OR if downloaded, it will show or play the content.

**Comment by PeeJWeeJ** [comment]
What/where is the desired interface for deleting a resource?

**Comment by dwsolberg** [comment]
Currently, there will be no way to delete a resource until we have the UI to do so.

**Comment by dwsolberg** [comment]
If we say that the audio selection is the default in the future, that means that the user will have no way to change that option unless we add the UI to do that. For now, I'm not going to include it unless I hear otherwise.

**Comment by dwsolberg** [comment]
@jag3773 @sampeckham  ^^ see above

**Comment by sampeckham** [comment]
Download icon changes to Trash Can icon once downloaded. Tap trash can and get Modal Prompt "Are you sure you want to delete..." Cancel / Delete options

**Comment by dwsolberg** [comment]
@sampeckham Currently, that's where the valid/not valid icon is going. Where should the validated/not validated icon go?
![screen shot 2015-11-30 at 5 39 36 pm](https://cloud.githubusercontent.com/assets/599596/11488075/66772284-9789-11e5-958e-ea864dda6ed4.png)

**Comment by sampeckham** [comment]
Hmm, I didn't see these icons or the feature in the spec, must have missed that, sorry.

What are these for though? Why would I be able to download an invalid file? Not sure the average user would understand (ie. I don't!). Can anyone point me to more info, details? Thanks.

**Comment by bknatterud** [comment]
The icons tell the user if the content they downloaded is cryptographically verified. This is probably something that @jag3773 should weigh in on. I'm assuming they want people to be able to know if content is verified but I would agree they are probably confusing to almost everyone.

**Comment by dwsolberg** [comment]
@jag3773 Another note is that none of the audio files currently have a signature, so they will always show as unverified.

**Comment by sampeckham** [comment]
Advocating for the average end user, who just wants the bible in their language I think the verification is irrelevant to them. It's lost on me (though I kind of see what it's about from this thread). As a user I should only be downloading a file that is complete, correct and "just works", otherwise why am I downloading it?

This is where the Product Owner steps in.... : )

**Comment by jag3773** [comment]
The cryptographic verification is there to ensure that the content has not changed since it was officially published *and* to signify who has signed the content.  Not everyone will be receiving the content direct from the server (e.g. peer to peer sharing), so the idea is to give an indication that the content has not been tampered with.  The digital signatures will become more and more important as we move in the direction of organizations signing their own content.

For the moment, @dwsolberg the audio/video will not have signatures in time for this release, so we are just talking about the JSON/USFM text files for now.  @sampeckham I would be fine if we silently succeeded in verifying the signature on the content but showed a warning dialog message upon failure.  Hence, we would not need a place in the list to show the "verified" status, only a pop up that would warn on failure.

Will that work?

**Comment by sampeckham** [comment]
That sounds good. Having a warning of a problem is a much better UX pattern. It draws attention at the right time with more information, than a yes/no indicator, especially when yes should be the norm. 

Suggest something along the lines of the Google Chrome https warning. "This site is not verified as secure are you sure you want to continue..."

**Comment by PeeJWeeJ** [comment]
Completed in latest android beta.

**Comment by dwsolberg** [comment]
done on ios
