### ISSUE TITLE
"Next Chapter" Old Green

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#141]
The "Next Chapter" button is still the old green color, which clashes terribly with the new UI green.

**Comment by PeeJWeeJ** [comment]
What color should it be?

**Comment by jag3773** [comment]
Let's just do the new green color for now.

**Comment by dwsolberg** [comment]
Done for iOS.

**Comment by PeeJWeeJ** [comment]
Change done for next release on android
