### ISSUE TITLE
Bluetooth sharing not working

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/uw-android#142]
Notes
======
Bluetooth sharing not working

Environment
======
Environment Key | Value
:----: | :----:
version | 2.3.0
build | 188
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw

**Comment by dwsolberg** [comment]
Assuming this is Android-only.

**Comment by PeeJWeeJ** [comment]
Should be working as well as expected in the latest build. Keep in mind we're using android's built in service for this, so we're at it's mercy as far as reliability.
