### ISSUE TITLE
WiFi direct crashed app

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/uw-android#143]
Notes
======
WiFi direct crashed app

Environment
======
Environment Key | Value
:----: | :----:
version | 2.3.0
build | 188
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw

**Comment by PeeJWeeJ** [comment]
This is fairly old, so probably not valid in the same manor. Re-open if it happens again.
