### ISSUE TITLE
app dies on trying to load a .ufw file

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/uw-android#144]
Notes
======
app dies on trying to load a .ufw file

Environment
======
Environment Key | Value
:----: | :----:
version | 2.3.0
build | 188
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw

**Comment by dwsolberg** [comment]
Assuming Android only.

**Comment by PeeJWeeJ** [comment]
If this is a problem with the latest build, re-open
