### ISSUE TITLE
Navigation Missing Down Arrows

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#146]
The chapter and resource navigation on Android have little down arrows that indicate they are clickable, but that is not present in iOS, makes it difficult to tell that is the way to navigate.

**Comment by dwsolberg** [comment]
Previously, an issue was created asking me to remove these arrows, and they do not appear on the design spec.

**Comment by jag3773** [comment]
I could live with it either way, but Android and iOS need to look the same here too.

**Comment by dwsolberg** [comment]
PJ, would you change this in Android?

**Comment by PeeJWeeJ** [comment]
This may be an instance where different user expectations dictate a difference in implementation for each platform.

iOS has a normal behavior of text being tappable. This generally isn't the case in android, so having an additional cue in the UI that text in the toolbar is actionable is more important. Without an indicator, it is just plain text and looks like a title, not a button.

**Comment by jag3773** [comment]
@sampeckham can you weigh in on this one?

**Comment by sampeckham** [comment]
@PeeJWeeJ is right in this behaviour.

iOS: All text, with some exception to the middle (title) text in the title bar is assumed actionable/clickable.
Android: Unless they are tabs (which have underlines) all actions have icons.

While the apps should generally look the same, it's always deemed poor design/lazy to make them identical for identical sake, and it often annoys the users when things are not quite the way they should on in their native OS.

The bigger issue is that the chapter titles are not being truncated and run into the language selector, overlapping badly.

**Comment by PeeJWeeJ** [comment]
As far as I can tell that's not an issue on Android, but that's a different issue anyway, so I'm going to close this.
