### ISSUE TITLE
Text Fills half the Screen on iOS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#149]
When reading OBS, the text box is filling ~half the screen in landscape mode, which looks very poor when there are only 1 or 2 lines of text.  The text box should only take up as much space as is necessary.

**Comment by dwsolberg** [comment]
Okay, the text will take up only as much space as necessary. Also, it will still take up only half the screen if the text is too long (the text will then scroll). Let me know if this is right.
