### ISSUE TITLE
Text Clipped in Full Screen Mode

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#150]
On Android, when going into full screen mode the text in the top menu is clipped instead of resized.

**Comment by PeeJWeeJ** [comment]
Changes in next update:

OBS text is scrollable
Size in portrait expands only to below the image
Size in landscape only expands to half the screen
Background is white in portrait, and black in landscape.

Let me know if any of this needs to be changed/tweaked.
