### ISSUE TITLE
Action Buttons for a Resource

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#152]
Right now, we have a similar thing going on for actions you can take on a resource as we do on the main screen, there are buttons everywhere!

Would be good to have a *single row* of buttons available, for en OBS this would be "Download Audio" and "Delete Text".  The "Download Audio" could change to "Delete Audio" if it is present on the device.

**Comment by PeeJWeeJ** [comment]
Duplicate. Relevant design change discussion is here: https://github.com/unfoldingWord-dev/uw-android/issues/140
