### ISSUE TITLE
navigated to PS 10 in the ulb and the app died

### ISSUE THREAD

**Issue by door43app** [unfoldingWord-dev/uw-android#154]
Notes
======
navigated to PS 10 in the ulb and the app died

Environment
======
Environment Key | Value
:----: | :----:
version | 2.3.0
build | 188
UDID | e37c929dc01796f
Android Release | 5.0.2
Android SDK | 21
Brand | samsung
Device | gt58wifi

**Comment by dwsolberg** [comment]
Assuming this is just Android.

**Comment by PeeJWeeJ** [comment]
Unable to duplicate. This may be due to an unrelated issue. Can you give any more information about how this happened?

**Comment by PeeJWeeJ** [comment]
Cannot reproduce
