### ISSUE TITLE
Add Support for \d

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#155]
Looks like we need to implement at least  italics for text in a \d.  In particular, this will be the descriptions under the chapter headings for some Psalms.

Ideally, this text should be italicized and 1 (maybe 2) points smaller than the main text.

**Comment by dwsolberg** [comment]
Jesse, could you put me to a sample usfm chapter/verse along with an image of how it should look?

**Comment by jag3773** [comment]
It's in the reference manual @dwsolberg

**Comment by dwsolberg** [comment]
Yes, but we can't implement everything from the manual. I want to know specifically how you are using it so that I can make sure we're implementing it in a way that works how you want.

**Comment by dwsolberg** [comment]
Done in iOS.

**Comment by PeeJWeeJ** [comment]
Change implemented for next android release
