### ISSUE TITLE
Support Selah

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#156]
Currently, the app is not handling "\qs Selah\qs*" correctly.  Psalm 3 provides an example.

Often "Selah" is italicized and right aligned on it's own line, let's do that.

**Comment by PeeJWeeJ** [comment]
In the USFM for psalm 3, there appears to be a "[" before Selah, e.g. " \qs [Selah\qs* "

Is this a typo? Or are we supposed to do something with this?

**Comment by PeeJWeeJ** [comment]
Done for next android release

**Comment by dwsolberg** [comment]
Done in iOS
