### ISSUE TITLE
Poetry Indentation (support for \q)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#157]
Poetry does not appear to be indented appropriately.  Usually the \q code should indicate some level of indentation.  Check Psalm 5 on https://bible.unfoldingword.org/ which shows the second line at the same indentation level as the first.  Or Psalm 5 at http://www.esvbible.org/Psalm%205/ which shows the second line indented farther than the first line.

For the app, I think it will look best to indent the second (and subsequent) lines *farther* than the first line.  Something like
```
1 Listen to my Cry, Yahweh;
    think about my groanings.
2 Listen to the sound of my Cry, my King and my God;
    for it is to you that I pray.
```

**Comment by PeeJWeeJ** [comment]
This is accomplished by putting a number after the \q tags. E.g. for your example:

1 \qListen to my Cry, Yahweh;
    \q2think about my groanings.
2 \qListen to the sound of my Cry, my King and my God;
    \q2for it is to you that I pray.

The app already supports this, other than the apparent bugs that have popped up.

**Comment by jag3773** [comment]
Please see https://github.com/unfoldingWord-dev/ts-android/issues/760#issuecomment-151682709 for the correct implementation.

**Comment by dwsolberg** [comment]
Here's how I'm doing it right now: If a given quoted line extends farther than the screen, I wrap the line and indent it slightly. 

I think you want to indent all quoted items in a verse. I think PJ's implementation might be the best answer. Otherwise, we're not following the USFM spec, which could cause issues later if we import other people's USFM files.

**Comment by PeeJWeeJ** [comment]
http://paratext.org/system/files/usfmReference2_4.pdf

Page #37

**Comment by jag3773** [comment]
"\q = \q1"

**Comment by dwsolberg** [comment]
Jesse, I'm not clear on \q = \q1
I know that's true, but my impression is that you wanted something to be extra indented, aka \q2

**Comment by jag3773** [comment]
A screenshot of the correct implementation is at https://github.com/unfoldingWord-dev/ts-android/issues/760#issuecomment-151682709.  The USFM that screenshot is showing is at https://github.com/unfoldingWord/ulb-en/blob/master/19-PSA.usfm#L49.

**Comment by PeeJWeeJ** [comment]
Fix complete for next release on android

**Comment by dwsolberg** [comment]
What did you do on this, PJ? I don't want to artificially indent against the USFM spec if there's another way.

**Comment by PeeJWeeJ** [comment]
@jag3773 After looking over the spec and discussing it with @dwsolberg, it looks like USFM indicates that \q tags apply to the following lines until either a different \q tag, or a paragraph break. 

Since the lines before the verses on psalm 2 have a \q tag, the way it was rendering before was actually correct according to the spec.

Should we override this? Or should this be changed in the text?

**Comment by jag3773** [comment]
I do see how you guys are reading the spec.  I think we are reading "the level of indent" differently.  I understand \q (or \q1) to be the first indent, e.g. not the standard alignment, but the first tab stop.  For example:
```
This is normal text
  This is the first level of indent (\q)
    This is the second level of indent (\q2)
This is normal again
```

However, that does contradict the formatting examples that they give.  Since both the ULB and UDB are currently expecting what I have described above, let's please implement it as I've described, and as is seen in https://github.com/unfoldingWord-dev/ts-android/issues/760#issuecomment-151682709.

**Comment by PeeJWeeJ** [comment]
Ok, in that case it should be working properly on android.

**Comment by dwsolberg** [comment]
@jag3773 That's how it is on iOS, too. It's just that when all the text is a quote, the first indent is the left margin.
