### ISSUE TITLE
Handle Line Breaks Better

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#158]
The USFM standard allows for line breaks within a verse that should not affect rendering.  Hence, if you check https://github.com/unfoldingWord/ulb-en/blob/master/19-PSA.usfm#L8984 and compare with Psalm 119:35 in the app you'll notice the problem.  The text of verse 35 should still start on the same line as the verse marker, even if there is a line break in the USFM.

**Comment by dwsolberg** [comment]
I don't see this issue.

**Comment by jag3773** [comment]
Looks like it is an Android only issue.

**Comment by PeeJWeeJ** [comment]
Fix complete for next release
