### ISSUE TITLE
Unexpected Indents

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#159]
Psalm 139:17 shows an unexpected indent, I can't figure out why based on the USFM source https://github.com/unfoldingWord/ulb-en/blob/master/19-PSA.usfm#L10476.

Proverbs 6:17 appears to show the same thing: https://github.com/unfoldingWord/ulb-en/blob/master/20-PRO.usfm#L661.

**Comment by dwsolberg** [comment]
I'm not seeing either of these issues, so I'm adding the Android tag. Let me know if you see an iOS issue.

**Comment by PeeJWeeJ** [comment]
This will be fixed in the next release.
