### ISSUE TITLE
Single Chapter Reference

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#160]
Please make sure that we implement what is described here: https://github.com/unfoldingWord-dev/ts-android/issues/756#issuecomment-151969555.  Each individual Psalm should be referred to as "Psalm {digit}" rather than "Psalms {digit}".

**Comment by dwsolberg** [comment]
Two Questions:
1. Should we do the same with Proverbs?

2. Is this a way we can add this to the JSON? Otherwise, there's really no way to do this in other languages unless we get the singular translation for each one.

**Comment by PeeJWeeJ** [comment]
I was thinking the same thing. Especially if there could be language specific changes in the future.

**Comment by jag3773** [comment]
@dwsolberg @PeeJWeeJ Per the comment I referenced above, the correct way to refer to a single chapter will be in the "\cl" key in the USFM (if it differs from the normal book name). Does that make sense?  In English we still say "Proverbs 29".

**Comment by jag3773** [comment]
Latest USFM now has this in Psalms, see https://github.com/unfoldingWord/ulb-en/blob/master/19-PSA.usfm#L14.

**Comment by dwsolberg** [comment]
Done in iOS.

**Comment by PeeJWeeJ** [comment]
Done on Android
