### ISSUE TITLE
Footnote Support

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#162]
There is a footnote in Hebrews 2 that is not displaying properly in the ULB or UDB on Android and iOS.  Mostly looks like the footnote support is partially implemented (or perhaps not at all).

**Comment by dwsolberg** [comment]
At least in iOS, footnotes are simply discarded. Would you like them to be inline in the text or appear at the bottom of the chapter text?

**Comment by PeeJWeeJ** [comment]
It shows up on android. What do you mean by "properly"? There seems to be a "+" symbol that wasn't included before, but is it displaying properly otherwise?

**Comment by jag3773** [comment]
I'm on build 168 for Android and the footnote is inline in the text as well as at the bottom, it is obviously not right.  It may not be an issue in the latest build you are working on?

**Comment by PeeJWeeJ** [comment]
Ok, let me know if it's still an issue on the next build.

**Comment by PeeJWeeJ** [comment]
Working as far as I can tell, so removing the android tag
