### ISSUE TITLE
App Dies when trying to import OBS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#176]
I transferred OBS English text and audio to another device via Bluetooth, which worked fine, but when I try to open it on the other device the app dies.  Both devices are Android 5.

**Comment by jag3773** [comment]
Note, this happens with just text also.  I tested OBS en and OBS vi and neither file would open on the destination device.

**Comment by PeeJWeeJ** [comment]
This should be working better now. Re-open with a Test-Fairy result if it continues to be a problem.
