### ISSUE TITLE
Translationkeyboard bug report

### ISSUE THREAD

**Issue by DavidGlovier** [unfoldingWord-dev/uw-android#43]
User cannot update keyboard at the Update Keyboard option and consistently gets the "Status Error: Invalid Update. Try again" error message.

Heis using a Nexus 7 tablet, supplied by WA for tech support during MAST deployments. Android version is 5.0.2 and kernel is 3.4.0-g154bef4.
![keyboard update problem](https://cloud.githubusercontent.com/assets/10064774/6182378/d6a76416-b2ff-11e4-84ae-c1b3fa322206.jpg)

**Comment by bknatterud** [comment]
is there a way to move this to the tK GitHub Project?

**Comment by DavidGlovier** [comment]
Probably, I am new in Github, But I'll see if I can figure out how to move it over there.
