### ISSUE TITLE
Incorporate Grandroid

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#47]
We need to have graphite rendering in the uW app.  See  https://github.com/silnrsi/grandroid and https://github.com/Door43/translationStudio2/issues/344.

**Comment by bknatterud** [comment]
ok, we will plan on that for 2.2.0

**Comment by PeeJWeeJ** [comment]
@bknatterud @jag3773 Is this still something that needs to be done? Or can this be closed?
