### ISSUE TITLE
Missing USFM Codes

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#51]
Check Acts 8, which has a footnote and a \m that need parsed.

**Comment by bknatterud** [comment]
Right now we are supporting the following codes...

\c
\v
\q
\q#
\b
\p
\pi (partial)
\f (in progress)

Are there other we should be supporting?

**Comment by jag3773** [comment]
Technically, anything in http://paratext.org/system/files/usfmReference2_4.pdf is fair game.

If you don't want to do all that upfront then I would highly recommend running a test that tells you what codes you are missing.  Every new translation we import has the possibility of using codes that are in that PDF.
