### ISSUE TITLE
Digital Signature Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#54]
Requires #53.

Clicking on the digital signature icon would bring up an informational window that lists the names of the organizations that have signed off on the content (right now that's just uW).  So, something like "This content has been signed by: [list of orgs]".  The above for verified content.

Non-verified content would give a short description of the problem in the info window, "Signature not available", "Signature did not match content", "Signing Identity [name of] has expired".

**Comment by bknatterud** [comment]
In the signature file there is an "si" property of "uW". Is there a place to get the additional entity information for uW? Or could that entity information be in the .sig file? Let me know.

**Comment by jag3773** [comment]
Yes, please check https://door43.org/en/dev/signing.  For uW the info is at https://pki.unfoldingword.org/uW-vk.pem.  For other signing identity's it will be in https://pki.unfoldingword.org/si/[slug].pem.
