### ISSUE TITLE
Drop Down Menus

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#55]
I think the app would look cleaner if the navigation and language/project selectors were drop down menus, instead of modal windows.

**Comment by bknatterud** [comment]
I think that would be ok on tablets, but on a lot of phones I think the modal makes more sense. No?

**Comment by jag3773** [comment]
On small screens we can keep it as is, but larger phones and tablets should definitely be drop down.

**Comment by bknatterud** [comment]
ok
