### ISSUE TITLE
Top Bar Checking Level Icons

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#56]
Related to #55, the checking level icon should be visible in the top bar while viewing a resource.  Clicking on that icon would show the status information and the short description of that checking level.

**Comment by bknatterud** [comment]
On smaller devices that would be hard to fit and I'm wondering if that is really necessary. When they are actually reading the text to people care about the checking level? If I want to see that I can go to the list of versions. No? Just a thought.

**Comment by jag3773** [comment]
The goal is to simplify the interface.  Currently finding the checking level information is a bit cumbersome.  Also, yes we do want them to know what the checking level is as they are reading it.  There is a world of difference between content checked to level 1 and content checked to level 3.

**Comment by jag3773** [comment]
This doesn't appear to be implemented.

1. Click on the checking level icons does nothing, but it should show a pop up with the short information on that checking level.

2. I'm not seeing the icons in the top bar.

See also #63.

**Comment by bknatterud** [comment]
This has been implemented now. Sorry, this one slipped by before.
