### ISSUE TITLE
Verify Icon Pops up Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#66]
Instead of the key at the bottom of the project list, clicking on a verification icon should pop up a window with a description.

**Comment by bknatterud** [comment]
I'm not sure a good way to do this with the current UI. On a tablet the user is already in a popover and potentially the touch target is small.
We are displaying verification information when the user taps on the "i" icon.

**Comment by bknatterud** [comment]
Put this extended info now in the info icon.
