### ISSUE TITLE
Show Details on Verify Errors

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#67]
Since we are signing books of the Bible individually, it would be helpful to show which books failed to verify.  This could show up in the pop described in #66.

**Comment by bknatterud** [comment]
Would it be ok to move this to 2.2.0?

**Comment by jag3773** [comment]
I think that depends on whether or not there are verification problems
right now.  If everything checks out then it would probably be ok to move
it back to 2.2.  Otherwise, we need to know what is causing the problems.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by bknatterud** [comment]
I don't remember off hand right now if everything checks out ok. I will take a look when I'm at the office in the morning.

**Comment by leok22** [comment]
Hey @bknatterud did you end up looking at this last week? If so, what's the status? Obviously we want to get this release done as soon as we can.

**Comment by bknatterud** [comment]
Yes. It looks like everything verifies like it should right now. The only one that does not is Bible -> unfoldingWord Literal Bible.

We will put a list of books of the Bible that did not verify in the info icon. I think that makes the most sense for now.

**Comment by bknatterud** [comment]
This is done and I am uploading a build with this shortly.
