### ISSUE TITLE
Verify Compression for USFM

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#69]
(Related to https://github.com/Door43/translationStudio2/issues/441)
The web server *may be* set to compress in-transit USFM payloads that are in excess of 10K if the client accepts that.

1. Does uW support that?  If not, what is the mimetype that the USFM texts are showing as, so that I can configure the in-transit compression to support that mimetype.
2. Is it working?
3. Should we lower the threshold to 1K?

**Comment by bknatterud** [comment]
it's currently coming down as an octet-stream

**Comment by jag3773** [comment]
Can you verify that it is being compressed?

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by PeeJWeeJ** [comment]
I believe this was verified, re-open if not.
