### ISSUE TITLE
First screen

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/uw-android#72]
At top where it says unfoldingWord add the app icon

**Comment by jag3773** [comment]
Let's either center this with the text or left align everything.  I think center would probably look better.

Also, let's get the icon with a transparent background, no need for the white around it I don't think.

**Comment by bknatterud** [comment]
Do you have artwork that is just the icon and no white around it? I'm not sure that I have that anywhere.

**Comment by bknatterud** [comment]
Bump

**Comment by jag3773** [comment]
https://unfoldingword.org/ has lots.  May be able to cut the book out of
https://unfoldingword.org/wp-content/uploads/2014/06/uW-vertical-logo-white.png
.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by bknatterud** [comment]
That helped. Thanks!
