### ISSUE TITLE
Select version page

### ISSUE THREAD

**Issue by leok22** [unfoldingWord-dev/uw-android#77]
a.	List all of the languages unexpanded
b.	When clicking on one click down to one

**Comment by jag3773** [comment]
This was supposed to be a slide effect, not a drop down (I see the task was written wrong).

The arrow on the language list is grainy, and generally unattractive besides that.  Can we get something that looks decent there?  Probably makes sense to move the arrow to the right to work in conjunction with the slide.

**Comment by bknatterud** [comment]
I think this is better and how you want it now.
