### ISSUE TITLE
App Dies

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#84]
After downloading, trying to click on the ULB causes the app to die.

**Comment by bknatterud** [comment]
I can't reproduce this one. There was an issue in build 133. But build 134 should be ok. And I can't reproduce the issue on 134. Are you able to consistently reproduce this issue?

**Comment by jag3773** [comment]
Yes, build 134, Samsung galaxy s5 on Android 5.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by bknatterud** [comment]
Ok. Even after uninstalling the app and re-installing?

**Comment by jag3773** [comment]
Yes.

**Comment by bknatterud** [comment]
Right now I am not able to reproduce this issue.

I tried with a fresh install and even tried by upgrading the app from the version on the Play Store.

Any other thoughts on how to reproduce?

**Comment by bknatterud** [comment]
Any thoughts? I still can't reproduce this.

**Comment by leok22** [comment]
@jag3773 @bknatterud I just opened ULB without issue on my Galaxy S5 Android 4.4.4
