### ISSUE TITLE
Multiple Download Fails

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#86]
On Bible, I tried downloaded all three versions, the first one completed, the others are still circling, 5+ minutes later.

**Comment by jag3773** [comment]
20+ minutes now and the 2 others have still not completed.

**Comment by jag3773** [comment]
Galaxy Tab 4, btw.

**Comment by bknatterud** [comment]
Ok, it looks like this one is fixed. But another user testing would be good.
