### ISSUE TITLE
Build App with Source Included

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#96]
For the final build we'll want all the content included.

**Comment by bknatterud** [comment]
You mean all of the languages and versions available for Bible and OBS?

**Comment by jag3773** [comment]
Yep.

**Comment by bknatterud** [comment]
I'm ready to do this once you give the ok that we can pull what is up.

**Comment by jag3773** [comment]
I don't see either of the English Bibles in build 160.  Please verify that you see 1 Peter in the ULB before pushing the next apk.
