### ISSUE TITLE
Update language information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#97]
Before the final build, we'll want the latest language information from tD.

**Comment by bknatterud** [comment]
Ok. You mean this JSON? http://td.unfoldingword.org/exports/langnames.json

**Comment by jag3773** [comment]
Yep.

**Comment by jag3773** [comment]
Doesn't look like this happened.  The display name for French was changed to "français" but the app is still showing "français, langue française".

**Comment by bknatterud** [comment]
I think I uploaded the wrong .apk yesterday. I just switched the .apk and it should be good now.

**Comment by jag3773** [comment]
Still wrong.

**Comment by bknatterud** [comment]
Ok, we pulled the JSON on May 13th when the issue was opened. It must have updated since then. We will pull the latest one now.
